################################################################################
# Big Data Analytics in Transportation (TU Dresden)
# Master Thesis
# This turns the network created using postgresql & PostGIS into a R-sf-network
################################################################################
source("./src/00_config.R")
source("./src/00_utils.R")

# Read in datatable containing shortest paths calculated by pgrouting
dt_shortest_paths <-
	read_csv("shortest_paths_cologne_edgeonly_202311141501.csv") %>% 
	as.data.table %>%
	distinct

# Read in streets generated by osm2po
dt_cologne <- read_csv("col_2po_4pgr_202311141523.csv") %>%
	as.data.table

# Extract edges in 'dt_cologne' identified by pgrouting
dt <- dt_cologne %>%
	inner_join(dt_shortest_paths, by = c("id" = "edge"))

dt <- dt %>%
	select(source, target, km, geom_way)

colnames(dt) <- c("from", "to", "km", "geometry")

# Create network
sf_network <- dt %>%
	st_as_sf(wkt = "geometry") %>%
	as_sfnetwork

sf_network %>% clusters


write_rds(sf_network, path_sf_network_colgone)